#define ENCODER_CLEAR_COUNTERS     0x20
#define ENCODER_CLEAR_COUNTER_X    0x21
#define ENCODER_CLEAR_COUNTER_Y    0x22
#define ENCODER_CLEAR_COUNTER_Z    0x23
#define ENCODER_CLEAR_COUNTER_W    0x24

#define ENCODER_READ_COUNTERS      0x60
#define ENCODER_READ_COUNTER_X     0x61
#define ENCODER_READ_COUNTER_Y     0x62
#define ENCODER_READ_COUNTER_Z     0x63
#define ENCODER_READ_COUNTER_W     0x64


#define ENCODER_LOAD_COUNTERS      0xE0
#define ENCODER_LOAD_COUNTER_X     0xE1
#define ENCODER_LOAD_COUNTER_Y     0xE2
#define ENCODER_LOAD_COUNTER_Z     0xE3
#define ENCODER_LOAD_COUNTER_W     0xE4
