#define ENCODER_CLEAR_COUNTERS     0x20
#define ENCODER_CLEAR_COUNTER_X    ENCODER_CLEAR_COUNTERS + 1
#define ENCODER_CLEAR_COUNTER_Y    ENCODER_CLEAR_COUNTERS + 2
#define ENCODER_CLEAR_COUNTER_Z    ENCODER_CLEAR_COUNTERS + 3
#define ENCODER_CLEAR_COUNTER_W    ENCODER_CLEAR_COUNTERS + 4

#define ENCODER_COUNTERS           0x60
#define ENCODER_COUNTER_X          ENCODER_COUNTERS + 1
#define ENCODER_COUNTER_Y          ENCODER_COUNTERS + 2
#define ENCODER_COUNTER_Z          ENCODER_COUNTERS + 3
#define ENCODER_COUNTER_W          ENCODER_COUNTERS + 4

#define ENCODER_TARGETS            0xE0
#define ENCODER_TARGET__X          ENCODER_TARGETS + 1
#define ENCODER_TARGET_Y           ENCODER_TARGETS + 2
#define ENCODER_TARGET_Z           ENCODER_TARGETS + 3
#define ENCODER_TARGET_W           ENCODER_TARGETS + 4
